BEGIN;
--
-- Create model Role
--
CREATE TABLE "core_role" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL UNIQUE, "description" text NOT NULL);
--
-- Create model Project
--
CREATE TABLE "core_project" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "project_name" varchar(255) NOT NULL, "description" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "owner_id" integer NOT NULL);
--
-- Create model File
--
CREATE TABLE "core_file" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "s3_key" varchar(1024) NOT NULL, "file_name" varchar(255) NOT NULL, "file_size" bigint NOT NULL, "storage_class" varchar(50) NOT NULL, "created_at" timestamp with time zone NOT NULL, "last_modified" timestamp with time zone NULL, "is_duplicate" boolean NOT NULL, "is_stale" boolean NOT NULL, "project_id" bigint NOT NULL);
--
-- Create model CostLog
--
CREATE TABLE "core_costlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "total_size_bytes" bigint NOT NULL, "monthly_cost" numeric(10, 2) NULL, "recorded_at" timestamp with time zone NOT NULL, "project_id" bigint NOT NULL);
--
-- Create model Recommendation
--
CREATE TABLE "core_recommendation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "recommendation_type" varchar(50) NOT NULL, "description" text NOT NULL, "potential_savings" numeric(10, 2) NULL, "created_at" timestamp with time zone NOT NULL, "project_id" bigint NOT NULL);
--
-- Create model Permission
--
CREATE TABLE "core_permission" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "granted_at" timestamp with time zone NOT NULL, "granted_by_id" integer NULL, "user_id" integer NOT NULL, "project_id" bigint NOT NULL, "role_id" bigint NOT NULL);
--
-- Create model AuditLog
--
CREATE TABLE "core_auditlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(100) NOT NULL, "resource_type" varchar(50) NOT NULL, "resource_id" integer NULL, "details" jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL, "user_id" integer NULL);
--
-- Create index core_projec_owner_i_0532ce_idx on field(s) owner of model project
--
CREATE INDEX "core_projec_owner_i_0532ce_idx" ON "core_project" ("owner_id");
--
-- Create index core_file_project_3513da_idx on field(s) project of model file
--
CREATE INDEX "core_file_project_3513da_idx" ON "core_file" ("project_id");
--
-- Create index core_file_is_dupl_853cfd_idx on field(s) is_duplicate of model file
--
CREATE INDEX "core_file_is_dupl_853cfd_idx" ON "core_file" ("is_duplicate");
--
-- Create index core_file_is_stal_43804b_idx on field(s) is_stale of model file
--
CREATE INDEX "core_file_is_stal_43804b_idx" ON "core_file" ("is_stale");
--
-- Create index core_costlo_project_e8c38a_idx on field(s) project of model costlog
--
CREATE INDEX "core_costlo_project_e8c38a_idx" ON "core_costlog" ("project_id");
--
-- Create index core_recomm_project_18c6e3_idx on field(s) project of model recommendation
--
CREATE INDEX "core_recomm_project_18c6e3_idx" ON "core_recommendation" ("project_id");
--
-- Create index core_permis_user_id_f42645_idx on field(s) user of model permission
--
CREATE INDEX "core_permis_user_id_f42645_idx" ON "core_permission" ("user_id");
--
-- Create index core_permis_project_e8fcc7_idx on field(s) project of model permission
--
CREATE INDEX "core_permis_project_e8fcc7_idx" ON "core_permission" ("project_id");
--
-- Create index core_permis_role_id_8f75cf_idx on field(s) role of model permission
--
CREATE INDEX "core_permis_role_id_8f75cf_idx" ON "core_permission" ("role_id");
--
-- Alter unique_together for permission (1 constraint(s))
--
ALTER TABLE "core_permission" ADD CONSTRAINT "core_permission_user_id_project_id_9b86d68a_uniq" UNIQUE ("user_id", "project_id");
CREATE INDEX "core_role_name_ca4cd9c7_like" ON "core_role" ("name" varchar_pattern_ops);
ALTER TABLE "core_project" ADD CONSTRAINT "core_project_owner_id_26945739_fk_auth_user_id" FOREIGN KEY ("owner_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_project_owner_id_26945739" ON "core_project" ("owner_id");
ALTER TABLE "core_file" ADD CONSTRAINT "core_file_project_id_fecee478_fk_core_project_id" FOREIGN KEY ("project_id") REFERENCES "core_project" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_file_project_id_fecee478" ON "core_file" ("project_id");
ALTER TABLE "core_costlog" ADD CONSTRAINT "core_costlog_project_id_80dc3ab4_fk_core_project_id" FOREIGN KEY ("project_id") REFERENCES "core_project" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_costlog_project_id_80dc3ab4" ON "core_costlog" ("project_id");
ALTER TABLE "core_recommendation" ADD CONSTRAINT "core_recommendation_project_id_e54cf58b_fk_core_project_id" FOREIGN KEY ("project_id") REFERENCES "core_project" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_recommendation_project_id_e54cf58b" ON "core_recommendation" ("project_id");
ALTER TABLE "core_permission" ADD CONSTRAINT "core_permission_granted_by_id_f34c5906_fk_auth_user_id" FOREIGN KEY ("granted_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_permission" ADD CONSTRAINT "core_permission_user_id_863744fa_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_permission" ADD CONSTRAINT "core_permission_project_id_095d63cd_fk_core_project_id" FOREIGN KEY ("project_id") REFERENCES "core_project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_permission" ADD CONSTRAINT "core_permission_role_id_ea2b8df5_fk_core_role_id" FOREIGN KEY ("role_id") REFERENCES "core_role" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_permission_granted_by_id_f34c5906" ON "core_permission" ("granted_by_id");
CREATE INDEX "core_permission_user_id_863744fa" ON "core_permission" ("user_id");
CREATE INDEX "core_permission_project_id_095d63cd" ON "core_permission" ("project_id");
CREATE INDEX "core_permission_role_id_ea2b8df5" ON "core_permission" ("role_id");
ALTER TABLE "core_auditlog" ADD CONSTRAINT "core_auditlog_user_id_3797aaab_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_auditlog_user_id_3797aaab" ON "core_auditlog" ("user_id");
CREATE INDEX "core_auditl_user_id_2ff9b7_idx" ON "core_auditlog" ("user_id");
CREATE INDEX "core_auditl_created_dc23ea_idx" ON "core_auditlog" ("created_at");
COMMIT;
