# Generated by Django 6.0.7 on 2026-07-14 20:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'core_role',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_project',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=1024)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('storage_class', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_stale', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.project')),
            ],
            options={
                'db_table': 'core_file',
            },
        ),
        migrations.CreateModel(
            name='CostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_size_bytes', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_logs', to='core.project')),
            ],
            options={
                'db_table': 'core_costlog',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('potential_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.project')),
            ],
            options={
                'db_table': 'core_recommendation',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_permissions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
            ],
            options={
                'db_table': 'core_permission',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_auditlog',
                'indexes': [models.Index(fields=['user'], name='core_auditl_user_id_2ff9b7_idx'), models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='core_projec_owner_i_0532ce_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['project'], name='core_file_project_3513da_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_duplicate'], name='core_file_is_dupl_853cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_stale'], name='core_file_is_stal_43804b_idx'),
        ),
        migrations.AddIndex(
            model_name='costlog',
            index=models.Index(fields=['project'], name='core_costlo_project_e8c38a_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['project'], name='core_recomm_project_18c6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['user'], name='core_permis_user_id_f42645_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['project'], name='core_permis_project_e8fcc7_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['role'], name='core_permis_role_id_8f75cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('user', 'project')},
        ),
    ]
